---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudTrail Bucket'
Parameters:
  Environment:
    Type: String
    Description: Environment Name
  CloudTrailS3BucketName:
    Description: 'The S3 bucket to store AWS CloudTrail files in.'
    Default: s3-acmecorp-cloudtrail
    Type: String
  AWSMasterAccountID:
    Type: String
    Description: AWS Account ID of Master Account ID.

  AWSProductionAccountID:
    Type: String
    Description: AWS Account ID of Production Operational Account ID.


Resources:
  CloudTrailBucket:
    DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "${CloudTrailS3BucketName}-${AWS::Region}"

  CloudTrailBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AWSCloudTrailBucketPermissionsCheck
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 's3:GetBucketAcl'
          Resource: !Sub '${CloudTrailBucket.Arn}'
        - Sid: AWSCloudTrailBucketDelivery
          Effect: Allow
          Action: 's3:PutObject'
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Resource:
            - !Sub '${CloudTrailBucket.Arn}/cloudtrail/AWSLogs/${AWSMasterAccountID}/*'
            - !Sub '${CloudTrailBucket.Arn}/cloudtrail/AWSLogs/${AWSProductionAccountID}/*'

          Condition:
            StringLike:
              's3:x-amz-acl': 'bucket-owner-full-control'