---
#====================================================================================================
# Description : CloudWatch Alarm Setup - Configures the SNS topic 
# Author      : Finnian Dempsey
# Date        : 30-01-2020
# Version     : 1.0.0
#====================================================================================================
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Configures an SNS topic for the CloudWatch Alarms to subscibe to'
#====================================================================================================
#                                             Parameters
#====================================================================================================
Parameters:
  #--------------------------------------------------------------------------------------------------
  AlarmTopicEmail:
    Description: The email address to send notification to if an alarm is triggered
    Type: String
  #--------------------------------------------------------------------------------------------------

#====================================================================================================
#                                              Resources
#====================================================================================================    
Resources:
  #--------------------------------------------------------------------------------------------------
  AlarmSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "CloudWatch-Alarm-Topic"
      Subscription: 
      - Endpoint: !Ref AlarmTopicEmail
        Protocol: email
  #--------------------------------------------------------------------------------------------------        
